### ISSUE TITLE
Packing SVG images

### ISSUE THREAD

**Issue by C00reNUT** [thierry7100/CutOptim#1]
Hello,

quick question -  Is there a easy way to make this work for SVG images (basically polygons filled with color and other polygons)?

Im looking for something that could solve bin packing problem of multiple images and this one looks promising.

**Comment by thierry7100** [comment]
Sorry, but I have used nanosvg library for processing svg files, and nanosvg doesn't handle images. And I have used nanosvg to avoid writing a svg reader, so I will be unable to help...
